### ISSUE TITLE
Remove this app

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/SysUpgrade#5]

**Comment by warpech** [comment]
I discussed this today with @joozek78. I think that SysUpgrade has served its purpose and should be removed now. When we want to try out ClientFiles on a different machine, we can just send a ZIP file.

@miyconst, @tomalec WDYT?

**Comment by tomalec** [comment]
I agree that this app is currently useless.
However, in my opinion app is better a migration/early-adopting/testing tool, than overwriting  `Starcounter/../sys` files via ZIP package:

- could be easily reverted,
- could be started/stopped in any moment, for any particular set of other apps
- could be versioned/updated via this repo,(instead of `Polymer7.0migration_package.zip`,`Polymer7.0Puppet3.0.zip`,`Polymer7.0Puppet3.0-with-dependencies.zip`)
- could be hosted here, without a need of email (virus scanners, filesize, searching)


To avoid confusion for any visitors of this repo, we can clean it, and add a note at README.md that there is no big migration in progress.

**Comment by miyconst** [comment]
I agree with what @tomalec says. We never know what Polymer is going to release in the future, and it is very likely this app will get handy again.

**Comment by warpech** [comment]
Problem is, that to address the values that you mention, this app would need to be actively maintained.

Right now it includes Polymer 1.3, so it is actually "SysDowngrade".

Maybe moving the files from https://github.com/Starcounter/Starcounter/tree/develop/src/BuildSystem/ClientFiles to a new `StarcounterSys` repo (with `master` branch and feature branches) would be a better idea?

**Comment by tomalec** [comment]
> to address the values that you mention, this app would need to be actively maintained.

I would say that to address those values, all we need is to remove everything from `https://github.com/StarcounterSamples/SysUpgrade/tree/master/SysUpgrade/wwwroot/sys` as  "there is no big migration in progress."

> Maybe moving the files from https://github.com/Starcounter/Starcounter/tree/develop/src/BuildSystem/ClientFiles to a new StarcounterSys repo (with master branch and feature branches) would be a better idea?

I'm affraid that this would require even bigger maintenance overhead, plus, to use such migration package client would have to build Starcounter, instead of just running .exe

**Comment by warpech** [comment]
> I would say that to address those values, all we need is to remove everything from https://github.com/StarcounterSamples/SysUpgrade/tree/master/SysUpgrade/wwwroot/sys as "there is no big migration in progress."

Ok, I will do that.

Since there is no universal acclaim for my idea, I am closing this issue.
